INSERT INTO STUDENT
(STUDENTID, NAME, CITY, COURSEID)
VALUES 
(1,'KASUN GAMAGE','KANDY',2),
(2,'DAINEL SAM','JAFFNA',3),
(3,'HANSI SILVA','COLOMBO',1),
(4, 'RANIDU HERATH','MATARA',3),
(5, 'PRANEETH WIJEYSINGHE','KANDY',4),
(6,'NUANTHI HERATH','RATHNAPURA',1);